//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ROMS.ActivationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IActivationService", Namespace="http://tempuri.org/")]
    public partial class ActivationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getuserlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback udfngetOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback udfngetOTPForProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback udfnproductAuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback udfnAuthenticateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActivationService() {
            this.Url = global::ROMS.Properties.Settings.Default.ROMS_ActivationService_ActivationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getuserlistCompletedEventHandler getuserlistCompleted;
        
        /// <remarks/>
        public event udfngetOTPCompletedEventHandler udfngetOTPCompleted;
        
        /// <remarks/>
        public event udfngetOTPForProductCompletedEventHandler udfngetOTPForProductCompleted;
        
        /// <remarks/>
        public event udfnproductAuthenticateCompletedEventHandler udfnproductAuthenticateCompleted;
        
        /// <remarks/>
        public event udfnAuthenticateCompletedEventHandler udfnAuthenticateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivationService/getuserlist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Customerrecords getuserlist([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usertype) {
            object[] results = this.Invoke("getuserlist", new object[] {
                        usertype});
            return ((Customerrecords)(results[0]));
        }
        
        /// <remarks/>
        public void getuserlistAsync(string usertype) {
            this.getuserlistAsync(usertype, null);
        }
        
        /// <remarks/>
        public void getuserlistAsync(string usertype, object userState) {
            if ((this.getuserlistOperationCompleted == null)) {
                this.getuserlistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetuserlistOperationCompleted);
            }
            this.InvokeAsync("getuserlist", new object[] {
                        usertype}, this.getuserlistOperationCompleted, userState);
        }
        
        private void OngetuserlistOperationCompleted(object arg) {
            if ((this.getuserlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getuserlistCompleted(this, new getuserlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivationService/udfngetOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string udfngetOTP([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string registrationkey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string versionno) {
            object[] results = this.Invoke("udfngetOTP", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void udfngetOTPAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno) {
            this.udfngetOTPAsync(name, mobileno, emailid, address, registrationkey, versionno, null);
        }
        
        /// <remarks/>
        public void udfngetOTPAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, object userState) {
            if ((this.udfngetOTPOperationCompleted == null)) {
                this.udfngetOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnudfngetOTPOperationCompleted);
            }
            this.InvokeAsync("udfngetOTP", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno}, this.udfngetOTPOperationCompleted, userState);
        }
        
        private void OnudfngetOTPOperationCompleted(object arg) {
            if ((this.udfngetOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.udfngetOTPCompleted(this, new udfngetOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivationService/udfngetOTPForProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string udfngetOTPForProduct([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string registrationkey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string versionno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ProductID) {
            object[] results = this.Invoke("udfngetOTPForProduct", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno,
                        ProductID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void udfngetOTPForProductAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, string ProductID) {
            this.udfngetOTPForProductAsync(name, mobileno, emailid, address, registrationkey, versionno, ProductID, null);
        }
        
        /// <remarks/>
        public void udfngetOTPForProductAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, string ProductID, object userState) {
            if ((this.udfngetOTPForProductOperationCompleted == null)) {
                this.udfngetOTPForProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnudfngetOTPForProductOperationCompleted);
            }
            this.InvokeAsync("udfngetOTPForProduct", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno,
                        ProductID}, this.udfngetOTPForProductOperationCompleted, userState);
        }
        
        private void OnudfngetOTPForProductOperationCompleted(object arg) {
            if ((this.udfngetOTPForProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.udfngetOTPForProductCompleted(this, new udfngetOTPForProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivationService/udfnproductAuthenticate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string udfnproductAuthenticate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string registrationkey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string versionno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string activationcode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productcode) {
            object[] results = this.Invoke("udfnproductAuthenticate", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno,
                        activationcode,
                        productcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void udfnproductAuthenticateAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, string activationcode, string productcode) {
            this.udfnproductAuthenticateAsync(name, mobileno, emailid, address, registrationkey, versionno, activationcode, productcode, null);
        }
        
        /// <remarks/>
        public void udfnproductAuthenticateAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, string activationcode, string productcode, object userState) {
            if ((this.udfnproductAuthenticateOperationCompleted == null)) {
                this.udfnproductAuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnudfnproductAuthenticateOperationCompleted);
            }
            this.InvokeAsync("udfnproductAuthenticate", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno,
                        activationcode,
                        productcode}, this.udfnproductAuthenticateOperationCompleted, userState);
        }
        
        private void OnudfnproductAuthenticateOperationCompleted(object arg) {
            if ((this.udfnproductAuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.udfnproductAuthenticateCompleted(this, new udfnproductAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivationService/udfnAuthenticate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string udfnAuthenticate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mobileno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string registrationkey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string versionno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string activationcode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productcode) {
            object[] results = this.Invoke("udfnAuthenticate", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno,
                        activationcode,
                        productcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void udfnAuthenticateAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, string activationcode, string productcode) {
            this.udfnAuthenticateAsync(name, mobileno, emailid, address, registrationkey, versionno, activationcode, productcode, null);
        }
        
        /// <remarks/>
        public void udfnAuthenticateAsync(string name, string mobileno, string emailid, string address, string registrationkey, string versionno, string activationcode, string productcode, object userState) {
            if ((this.udfnAuthenticateOperationCompleted == null)) {
                this.udfnAuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnudfnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("udfnAuthenticate", new object[] {
                        name,
                        mobileno,
                        emailid,
                        address,
                        registrationkey,
                        versionno,
                        activationcode,
                        productcode}, this.udfnAuthenticateOperationCompleted, userState);
        }
        
        private void OnudfnAuthenticateOperationCompleted(object arg) {
            if ((this.udfnAuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.udfnAuthenticateCompleted(this, new udfnAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SSSAccountsActivationService")]
    public partial class Customerrecords {
        
        private System.Data.DataSet customerdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet customerdetails {
            get {
                return this.customerdetailsField;
            }
            set {
                this.customerdetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getuserlistCompletedEventHandler(object sender, getuserlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getuserlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getuserlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customerrecords Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customerrecords)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void udfngetOTPCompletedEventHandler(object sender, udfngetOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class udfngetOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal udfngetOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void udfngetOTPForProductCompletedEventHandler(object sender, udfngetOTPForProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class udfngetOTPForProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal udfngetOTPForProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void udfnproductAuthenticateCompletedEventHandler(object sender, udfnproductAuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class udfnproductAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal udfnproductAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void udfnAuthenticateCompletedEventHandler(object sender, udfnAuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class udfnAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal udfnAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591